export const DONATION_ADD_REQUEST = "DONATION_ADD_REQUEST";
export const DONATION_ADD_SUCCESS = "DONATION_ADD_SUCCESS";
export const DONATION_ADD_FAIL = "DONATION_ADD_FAIL";

export const DONATION_UPDATE_REQUEST = "DONATION_UPDATE_REQUEST";
export const DONATION_UPDATE_SUCCESS = "DONATION_UPDATE_SUCCESS";
export const DONATION_UPDATE_FAIL = "DONATION_UPDATE_FAIL";

export const DONATION_DELETE_REQUEST = "DONATION_DELETE_REQUEST";
export const DONATION_DELETE_SUCCESS = "DONATION_DELETE_SUCCESS";
export const DONATION_DELETE_FAIL = "DONATION_DELETE_FAIL";

export const DONATION_GET_REQUEST = "DONATION_GET_REQUEST";
export const DONATION_GET_SUCCESS = "DONATION_GET_SUCCESS";
export const DONATION_GET_FAIL = "DONATION_GET_FAIL";
