export const DONATION_IN_ADD_REQUEST = "DONATION_IN_ADD_REQUEST";
export const DONATION_IN_ADD_SUCCESS = "DONATION_IN_ADD_SUCCESS";
export const DONATION_IN_ADD_FAIL = "DONATION_IN_ADD_FAIL";

export const DONATION_IN_UPDATE_REQUEST = "DONATION_IN_UPDATE_REQUEST";
export const DONATION_IN_UPDATE_SUCCESS = "DONATION_IN_UPDATE_SUCCESS";
export const DONATION_IN_UPDATE_FAIL = "DONATION_IN_UPDATE_FAIL";

export const DONATION_IN_DELETE_REQUEST = "DONATION_IN_DELETE_REQUEST";
export const DONATION_IN_DELETE_SUCCESS = "DONATION_IN_DELETE_SUCCESS";
export const DONATION_IN_DELETE_FAIL = "DONATION_IN_DELETE_FAIL";

export const DONATION_IN_GET_REQUEST = "DONATION_IN_GET_REQUEST";
export const DONATION_IN_GET_SUCCESS = "DONATION_IN_GET_SUCCESS";
export const DONATION_IN_GET_FAIL = "DONATION_IN_GET_FAIL";
