export const DONOR_DONEE_ADD_REQUEST = "DONOR_DONEE_ADD_REQUEST";
export const DONOR_DONEE_ADD_SUCCESS = "DONOR_DONEE_ADD_SUCCESS";
export const DONOR_DONEE_ADD_FAIL = "DONOR_DONEE_ADD_FAIL";

export const DONOR_DONEE_UPDATE_REQUEST = "DONOR_DONEE_UPDATE_REQUEST";
export const DONOR_DONEE_UPDATE_SUCCESS = "DONOR_DONEE_UPDATE_SUCCESS";
export const DONOR_DONEE_UPDATE_FAIL = "DONOR_DONEE_UPDATE_FAIL";

export const DONOR_DONEE_DELETE_REQUEST = "DONOR_DONEE_DELETE_REQUEST";
export const DONOR_DONEE_DELETE_SUCCESS = "DONOR_DONEE_DELETE_SUCCESS";
export const DONOR_DONEE_DELETE_FAIL = "DONOR_DONEE_DELETE_FAIL";

export const DONOR_DONEE_GET_REQUEST = "DONOR_DONEE_GET_REQUEST";
export const DONOR_DONEE_GET_SUCCESS = "DONOR_DONEE_GET_SUCCESS";
export const DONOR_DONEE_GET_FAIL = "DONOR_DONEE_GET_FAIL";

export const DONOR_DONEE_DETAIL_REQUEST = "DONOR_DONEE_DETAIL_REQUEST";
export const DONOR_DONEE_DETAIL_SUCCESS = "DONOR_DONEE_DETAIL_SUCCESS";
export const DONOR_DONEE_DETAIL_FAIL = "DONOR_DONEE_DETAIL_FAIL";
