export const ITEM_ADD_REQUEST = "ITEM_ADD_REQUEST";
export const ITEM_ADD_SUCCESS = "ITEM_ADD_SUCCESS";
export const ITEM_ADD_FAIL = "ITEM_ADD_FAIL";

export const ITEM_UPDATE_REQUEST = "ITEM_UPDATE_REQUEST";
export const ITEM_UPDATE_SUCCESS = "ITEM_UPDATE_SUCCESS";
export const ITEM_UPDATE_FAIL = "ITEM_UPDATE_FAIL";

export const ITEM_DELETE_REQUEST = "ITEM_DELETE_REQUEST";
export const ITEM_DELETE_SUCCESS = "ITEM_DELETE_SUCCESS";
export const ITEM_DELETE_FAIL = "ITEM_DELETE_FAIL";

export const ITEM_GET_REQUEST = "ITEM_GET_REQUEST";
export const ITEM_GET_SUCCESS = "ITEM_GET_SUCCESS";
export const ITEM_GET_FAIL = "ITEM_GET_FAIL";

export const ITEM_GET_DONATE_ITEM_REQUEST = "ITEM_GET_DONATE_ITEM_REQUEST";
export const ITEM_GET_DONATE_ITEM_SUCCESS = "ITEM_GET_DONATE_ITEM_SUCCESS";
export const ITEM_GET_DONATE_ITEM_FAIL = "ITEM_GET_DONATE_ITEM__FAIL";
